name: build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libjansson-dev

      - name: Build
        run: |
          gcc main.c /usr/lib/x86_64-linux-gnu/libjansson.a -o featured-list-creator

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: featured-list-creator
          path: featured-list-creator
